# Generated by Django 5.2.5 on 2025-08-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_education',
            field=models.CharField(null=True),
        ),
        migrations.DeleteModel(
            name='EmployeeEducation',
        ),
    ]
