# Generated by Django 5.2.5 on 2025-08-18 08:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_employee_emp_education_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leavebalance',
            options={'ordering': ['-year', 'employee__emp_name'], 'verbose_name': 'Leave Balance', 'verbose_name_plural': 'Leave Balances'},
        ),
        migrations.AlterModelOptions(
            name='leavetype',
            options={'ordering': ['leave_name'], 'verbose_name': 'Leave Type', 'verbose_name_plural': 'Leave Types'},
        ),
        migrations.RenameField(
            model_name='leavemanagement',
            old_name='approved_on',
            new_name='validated_on',
        ),
        migrations.RenameField(
            model_name='leavetype',
            old_name='name',
            new_name='leave_name',
        ),
        migrations.RemoveField(
            model_name='leavemanagement',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='leavemanagement',
            name='rejection_reason',
        ),
        migrations.AddField(
            model_name='leavemanagement',
            name='incharge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incharge', to='app.employee'),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_title',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='annual_allocation',
            field=models.IntegerField(default=20, help_text='Default annual allocation in days', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='min_notice_days',
            field=models.IntegerField(default=0, help_text='Minimum notice required in days'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['job_title', 'is_active'], name='job_job_tit_3d1a91_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['dept', 'is_active'], name='job_dept_id_bbf5d2_idx'),
        ),
    ]
