# Generated by Django 5.2.5 on 2025-08-18 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_leavebalance_options_alter_leavetype_options_and_more'),
    ]

operations = [
    migrations.RemoveField(
        model_name='employee',
        name='dept',
    ),
    migrations.AddField(
        model_name='employee',
        name='job',
        field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.job'),
        preserve_default=False,
    ),
]
