# Generated by Django 5.2.5 on 2025-08-18 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_employee_dept_employee_job'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leavebalance',
            options={'ordering': ['year', 'employee'], 'verbose_name': 'Leave Balance', 'verbose_name_plural': 'Leave Balances'},
        ),
        migrations.AlterModelOptions(
            name='leavetype',
            options={'ordering': ['name'], 'verbose_name': 'Leave Type', 'verbose_name_plural': 'Leave Types'},
        ),
        migrations.RemoveIndex(
            model_name='leavebalance',
            name='leave_balan_employe_3c91bc_idx',
        ),
        migrations.RemoveIndex(
            model_name='leavebalance',
            name='leave_balan_year_971b22_idx',
        ),
        migrations.RenameField(
            model_name='leavebalance',
            old_name='carried_forward',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='leavetype',
            old_name='leave_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='allocated_days',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='used_days',
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='app.leavetype'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='annual_allocation',
            field=models.IntegerField(default=20, help_text='Default annual allocation in days'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='min_notice_days',
            field=models.IntegerField(default=1, help_text='Minimum notice required in days'),
        ),
    ]
