# Generated by Django 5.2.5 on 2025-08-18 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_leavebalance_options_alter_leavetype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leavetype',
            options={'ordering': ['leave_name'], 'verbose_name': 'Leave Type', 'verbose_name_plural': 'Leave Types'},
        ),
        migrations.RenameField(
            model_name='leavetype',
            old_name='name',
            new_name='leave_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='dept',
        ),
        migrations.AddField(
            model_name='employee',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.job'),
        ),
    ]
