# Generated by Django 5.2.5 on 2025-08-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_employee_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeestatus',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
