# Generated by Django 5.2.5 on 2025-08-19 14:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDepartment',
            fields=[
                ('dept_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'employee_department',
                'ordering': ['dept_name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('leave_type_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leave_name', models.CharField(help_text='e.g., Annual Leave, Sick Leave, Personal Leave', max_length=50)),
                ('annual_allocation', models.IntegerField(default=20, help_text='Default annual allocation in days')),
                ('carry_forward', models.BooleanField(default=False, help_text='Can unused leaves be carried to next year')),
                ('max_consecutive_days', models.IntegerField(default=7, help_text='Maximum consecutive days allowed')),
                ('min_notice_days', models.IntegerField(default=1, help_text='Minimum notice required in days')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leave Type',
                'verbose_name_plural': 'Leave Types',
                'db_table': 'leave_type',
                'ordering': ['leave_name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('hire_date', models.DateField()),
                ('resignation_date', models.DateField(blank=True, null=True)),
                ('emp_education', models.CharField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employee',
                'ordering': ['emp_name'],
                'indexes': [models.Index(fields=['email'], name='employee_email_c0d4f7_idx'), models.Index(fields=['is_active'], name='employee_is_acti_b3d696_idx'), models.Index(fields=['hire_date'], name='employee_hire_da_ee483f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(db_index=True, max_length=100, unique=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='app.employeedepartment')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'job',
                'ordering': ['job_title'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeStatus',
            fields=[
                ('st_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='app.employee')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_statuses', to='app.job')),
            ],
            options={
                'verbose_name': 'Employee Status',
                'verbose_name_plural': 'Employee Statuses',
                'db_table': 'employee_status',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='LeaveManagement',
            fields=[
                ('leave_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days_requested', models.IntegerField(editable=False)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('validated_on', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='app.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='app.leavetype')),
            ],
            options={
                'verbose_name': 'Leave Application',
                'verbose_name_plural': 'Leave Applications',
                'db_table': 'leave_management',
                'ordering': ['-applied_on'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('balance_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('balance', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='app.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='app.leavetype')),
            ],
            options={
                'verbose_name': 'Leave Balance',
                'verbose_name_plural': 'Leave Balances',
                'db_table': 'leave_balance',
                'ordering': ['year', 'employee'],
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['job_title', 'is_active'], name='job_job_tit_3d1a91_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['dept', 'is_active'], name='job_dept_id_bbf5d2_idx'),
        ),
        migrations.AddIndex(
            model_name='employeestatus',
            index=models.Index(fields=['employee', 'is_current'], name='employee_st_employe_4d2125_idx'),
        ),
        migrations.AddIndex(
            model_name='employeestatus',
            index=models.Index(fields=['start_date'], name='employee_st_start_d_00484b_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeestatus',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('employee',), name='unique_current_status_per_employee'),
        ),
        migrations.AddIndex(
            model_name='leavemanagement',
            index=models.Index(fields=['employee', 'status'], name='leave_manag_employe_d13186_idx'),
        ),
        migrations.AddIndex(
            model_name='leavemanagement',
            index=models.Index(fields=['start_date', 'end_date'], name='leave_manag_start_d_dc2e1c_idx'),
        ),
        migrations.AddIndex(
            model_name='leavemanagement',
            index=models.Index(fields=['status'], name='leave_manag_status_093add_idx'),
        ),
        migrations.AddConstraint(
            model_name='leavebalance',
            constraint=models.UniqueConstraint(fields=('employee', 'leave_type', 'year'), name='unique_leave_balance_per_year'),
        ),
    ]
