# Generated by Django 5.2.5 on 2025-08-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_job_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavemanagement',
            name='year',
            field=models.IntegerField(db_index=True, default=2025, editable=False),
            preserve_default=False,
        ),
    ]
